channels:
- conda-forge
dependencies:
- python=3.12.10
- pip
- pip:
  - mlflow==3.2.0
  - cloudpickle==3.1.1
  - lightgbm==4.6.0
  - matplotlib==3.10.5
  - numpy==2.3.2
  - pandas==2.3.1
  - psutil==7.0.0
  - pyarrow==21.0.0
  - scikit-learn==1.5.0
  - scipy==1.16.1
name: mlflow-env
